[package]
name = "executer"
version = "0.1.0"
edition = "2018"
description = "A executer app built in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
chrono = "0.4.19"
settimeout = "0.1.2"
futures = "0.3.16"